include colors/gruvbox-dark.conf

font_family     JetBrainsMono Nerd Font Mono
font_size       13

disable_ligatures no
enable_audio_bell no

shell fish
shel_integration disable_ligatures

cursor_shape     block

url_style curly

remember_window_size no 


initial_window_widht 78c
initial_window_height 23c
window_padding_width 30
coursor_blink_interval 0

background_opacity 0.90
scrollbar_handle_opacity 0
scrollbar_track_opacity 0
scrollbar_track_hover_opacity 0
confirm_os_window_close 0

# -- Performance settings 
sync_to_monitor no

# -- Perf
repaint_delay 8
input_delay   3

cursor_trail 3
